import { expect, test, type Page } from '@playwright/test'

async function navigate(page: Page, label: string) {
  const menu = page.getByRole('button', { name: 'Open menu', exact: true })
  if (await menu.isVisible()) await menu.click()
  await page.getByRole('button', { name: label, exact: true }).click()
}

test('snapshot, plan, scenario, persistent feedback, history and deletion', async ({ page }, info) => {
  const exceptions: string[] = []
  page.on('pageerror', e => exceptions.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Create my plan' })).toBeVisible()
  await expect(page.getByLabel('Monthly take-home income', { exact: true })).toHaveValue('4200')
  await page.screenshot({ path: info.outputPath('snapshot.png'), fullPage: true })
  const response = page.waitForResponse(r => r.url().endsWith('/v1/analyses') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create my plan' }).click()
  const result = await (await response).json()
  expect(result.metrics.monthly_surplus).toBe('1300.00')
  expect(result.metrics.allocated_monthly).toBe('1300.00')
  expect(result.status).toBe('complete')
  console.log(`Explanation mode: ${result.ai_status}; model: ${result.model_version || 'none'}`)
  await expect(page.getByRole('heading', { name: 'Your next good money moves' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('plan.png'), fullPage: true })
  await page.getByRole('button', { name: 'Plan to do', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'Plan to do', exact: true }).first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Helpful', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Scenario flexible spending').fill('400')
  await page.getByRole('button', { name: 'Compare scenario' }).click()
  await expect(page.getByText('$1,500.00 monthly surplus')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Plan to do', exact: true }).first()).toHaveAttribute('aria-pressed', 'true')
  await navigate(page, 'Plan history')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await navigate(page, 'Learning library')
  await expect(page.locator('.source-card')).toHaveCount(6)
  await navigate(page, 'Privacy & data')
  await page.getByRole('checkbox').check()
  await expect(page.getByText('Your preference has been saved.')).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export my data' }).click()
  expect((await download).suggestedFilename()).toBe('wealthguide-export.json')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Delete my data' }).click()
  await expect(page.getByText('Your previous session and all its saved data were deleted.')).toBeVisible()
  await navigate(page, 'Plan history')
  await expect(page.getByRole('heading', { name: 'A fresh start.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(exceptions).toEqual([])
})
