import { expect, test, type Page } from '@playwright/test'

async function navigate(page: Page, label: string) {
  const menu = page.getByRole('button', { name: 'Open menu', exact: true })
  if (await menu.isVisible()) await menu.click()
  await page.getByRole('button', { name: label, exact: true }).click()
}

test('snapshot, plan, scenario, persistent feedback, history and deletion', async ({ page }, info) => {
  const exceptions: string[] = []
  page.on('pageerror', e => exceptions.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Good guidance starts with a conversation.' })).toBeVisible()
  await navigate(page, 'Financial snapshot')
  await expect(page.getByRole('button', { name: 'Create my plan' })).toBeVisible()
  await expect(page.getByLabel('Monthly take-home income', { exact: true })).toHaveValue('4200')
  await page.screenshot({ path: info.outputPath('snapshot.png'), fullPage: true })
  const response = page.waitForResponse(r => r.url().endsWith('/v1/analyses') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create my plan' }).click()
  const result = await (await response).json()
  expect(result.metrics.monthly_surplus).toBe('1300.00')
  expect(result.metrics.allocated_monthly).toBe('1300.00')
  expect(result.status).toBe('complete')
  console.log(`Explanation mode: ${result.ai_status}; model: ${result.model_version || 'none'}`)
  await expect(page.getByRole('heading', { name: 'Your next good money moves' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('plan.png'), fullPage: true })
  await page.getByRole('button', { name: 'Plan to do', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'Plan to do', exact: true }).first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Helpful', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Scenario flexible spending').fill('400')
  await page.getByRole('button', { name: 'Compare scenario' }).click()
  await expect(page.getByText('$1,500.00 monthly surplus')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Plan to do', exact: true }).first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Ask about this plan' }).click()
  await expect(page.getByRole('checkbox', { name: 'Include my selected saved plan' })).toBeChecked()
  await navigate(page, 'Plan history')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await navigate(page, 'Learning library')
  await expect(page.locator('.source-card')).toHaveCount(6)
  await navigate(page, 'Privacy & data')
  await page.getByRole('checkbox').click()
  await expect(page.getByRole('checkbox')).toBeChecked()
  await expect(page.getByText('Your preference has been saved.')).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export my data' }).click()
  expect((await download).suggestedFilename()).toBe('wealthguide-export.json')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Delete my data' }).click()
  await expect(page.getByText('Your previous session and all its saved data were deleted.')).toBeVisible()
  await navigate(page, 'Plan history')
  await expect(page.getByRole('heading', { name: 'A fresh start.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(exceptions).toEqual([])
})

test('chat persistence and reviewed draft handoff', async ({ page }, info) => {
  const exceptions: string[] = []
  page.on('pageerror', e => exceptions.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Build my snapshot', exact: true })).toBeEnabled()
  await page.screenshot({ path: info.outputPath('chat.png'), fullPage: true })
  await page.getByRole('button', { name: 'Build my snapshot', exact: true }).click()
  await expect(page.getByLabel('Message your WealthGuide')).toHaveValue('Help me build my financial snapshot. What should I start with?')
  const posted = page.waitForResponse(r => r.url().endsWith('/v1/chat') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send message' }).click()
  const turn = await (await posted).json()
  expect(turn.status).toBe('complete')
  await expect(page.locator('.chat-bubble.assistant')).toContainText(turn.answer)
  await expect(page.getByLabel('Message your WealthGuide')).toBeFocused()
  await expect(page.getByRole('button', { name: 'Review financial snapshot' })).toBeDisabled()
  await page.reload()
  await expect(page.locator('.chat-bubble.user')).toHaveCount(1)
  await expect(page.locator('.chat-bubble.assistant')).toContainText(turn.answer)

  // AI output fixture isolates the form-handoff UI; API persistence/access use the real server above.
  await page.route('**/api/v1/chat', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    const body = route.request().postDataJSON()
    const draft = { cash_balance: '7000', monthly_income: '4500', essential_expenses: '2000', discretionary_expenses: '500', emergency_fund: '1000', debts: [] }
    await route.fulfill({ json: { ...turn, id: crypto.randomUUID(), request_id: body.request_id, message: body.message,
      answer: 'Your details are ready. Review the snapshot before creating your plan.', ai_status: 'generated',
      draft, missing_fields: [], review_issues: [], sources: [],
      snapshot: { ...draft, as_of: new Date().toLocaleDateString('en-CA'), currency: 'USD', emergency_months: 3, goal: null, employer_match: null } } })
  })
  await page.getByLabel('Message your WealthGuide').fill('Here are my fictional details.')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByRole('button', { name: 'Review financial snapshot' })).toBeEnabled()
  await page.screenshot({ path: info.outputPath('chat-ready.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Review financial snapshot' }).click()
  await expect(page.getByLabel('Total cash balance', { exact: true })).toHaveValue('7000')
  await expect(page.getByLabel('Monthly take-home income', { exact: true })).toHaveValue('4500')
  await expect(page.getByRole('button', { name: 'Create my plan' })).toBeVisible()
  await navigate(page, 'Plan history')
  await expect(page.getByRole('heading', { name: 'A fresh start.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await navigate(page, 'Privacy & data')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Delete my data' }).click()
  await expect(page.getByText('Your previous session and all its saved data were deleted.')).toBeVisible()
  await navigate(page, 'Chat with your guide')
  await expect(page.getByRole('button', { name: 'Build my snapshot', exact: true })).toBeVisible()
  await expect(page.locator('.chat-bubble.user')).toHaveCount(0)
  expect(exceptions).toEqual([])
})
