import { useState } from 'react'
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronDown, CircleHelp, Code2, Info, MessageCircle, ThumbsDown, ThumbsUp, TrendingUp, Wallet } from 'lucide-react'
import { api, errorMessage } from './api'
import { formatMoney } from './SnapshotForm'
import type { Analysis, Feedback, Plan } from './types'

export default function PlanView({ analysis, onEdit, onChat, onFeedback }: { analysis: Analysis; onEdit: () => void; onChat: () => void; onFeedback: (feedback: Feedback) => Promise<void> }) {
  const [feedbackBusy, setFeedbackBusy] = useState(false)
  const [notice, setNotice] = useState('')
  const [comment, setComment] = useState(analysis.feedback.find(f => f.action_id === 'overview')?.comment || '')
  const [spending, setSpending] = useState(analysis.snapshot.discretionary_expenses)
  const [scenario, setScenario] = useState<Plan | null>(null)
  const [scenarioBusy, setScenarioBusy] = useState(false)
  const explanation = analysis.ai_explanation
  const overview = analysis.feedback.find(f => f.action_id === 'overview')
  const coverage = Math.min(100, Number(analysis.snapshot.emergency_fund) / Math.max(Number(analysis.metrics.emergency_target), 1) * 100)
  async function feedback(value: Feedback) {
    setNotice(''); setFeedbackBusy(true)
    try { await onFeedback(value); setNotice('Feedback saved. Thank you.') } catch (e) { setNotice(errorMessage(e)) } finally { setFeedbackBusy(false) }
  }
  async function compare() {
    setScenarioBusy(true); setNotice('')
    try { setScenario(await api<Plan>('/v1/scenarios', { method: 'POST', body: JSON.stringify({ ...analysis.snapshot, discretionary_expenses: spending }) })) }
    catch (e) { setNotice(errorMessage(e)) } finally { setScenarioBusy(false) }
  }

  return <div className="plan-layout">
    <section className="plan-hero"><div className="hero-copy"><span className="hero-badge"><CheckCircle2 size={15} /> {analysis.ai_status === 'generated' ? 'AI explanation · checked calculations' : analysis.ai_status === 'fallback' ? 'AI unavailable · standard explanation' : 'Standard explanation · checked calculations'}</span><h2>{explanation?.headline || 'Your next steps are taking shape.'}</h2><p>{explanation?.summary || 'Your calculations are saved. The explanation is being prepared.'}</p></div><div className="reserve-visual"><span>Emergency cushion</span><strong>{Math.round(coverage)}<small>%</small></strong><progress value={coverage} max={100} aria-label="Emergency target saved" /><span>{formatMoney(analysis.snapshot.emergency_fund)} of {formatMoney(analysis.metrics.emergency_target)}</span></div></section>
    <div className="metric-grid"><div className="metric-card"><span><Wallet size={16} />Monthly room to save</span><strong className={Number(analysis.metrics.monthly_surplus) < 0 ? 'negative' : ''}>{formatMoney(analysis.metrics.monthly_surplus)}</strong><small>After spending and debt minimums</small></div><div className="metric-card"><span><TrendingUp size={16} />Assigned in this plan</span><strong>{formatMoney(analysis.metrics.allocated_monthly)}<small> / mo</small></strong><small>Every dollar has one job</small></div><div className="metric-card"><span><CircleHelp size={16} />Still unallocated</span><strong>{formatMoney(analysis.metrics.unallocated_monthly)}<small> / mo</small></strong><small>Available for your next decision</small></div></div>
    <div className="content-heading"><h2>Your next good money moves</h2><div className="plan-tools"><button className="text-button" onClick={onChat}><MessageCircle size={15} />Ask about this plan</button><button className="text-button" onClick={onEdit}>Update snapshot <ArrowRight size={15} /></button></div></div>
    <div className="action-list">{analysis.actions.map((action, i) => {
      const status = analysis.feedback.find(f => f.action_id === action.id)?.action_status
      return <article className={`action-card ${i === 0 ? 'priority-card' : ''}`} key={action.id}><div className="action-top"><span className="action-number">{String(i + 1).padStart(2, '0')}</span><div className="action-body"><div className="action-kicker">{i === 0 ? 'START HERE' : 'THEN, BUILD ON IT'}{status === 'completed' && <span className="completed"><Check size={13} /> Self-reported done</span>}</div><h3>{action.title}</h3><p>{explanation?.actions.find(a => a.action_id === action.id)?.explanation || action.reason}</p></div><div className="action-amount">{action.kind === 'allocation' ? <><strong>{formatMoney(action.amount)}</strong><span>per month</span></> : <span className="review-badge">Worth reviewing</span>}</div></div><div className="action-bottom"><details><summary><Info size={14} /> Why this step? <ChevronDown size={13} /></summary><div className="action-details"><p>{action.reason}</p><div className="calculation">{action.calculation}</div>{analysis.sources.filter(s => action.source_ids.includes(s.id)).map(s => <a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.publisher}: {s.title} <ArrowUpRight size={12} /></a>)}</div></details><div className="action-buttons" aria-label={`Progress for ${action.title}`}>
        {(['accepted', 'completed', 'dismissed'] as const).map(s => <button key={s} disabled={feedbackBusy} aria-pressed={status === s} className={`status-button ${status === s ? 'selected' : ''}`} onClick={() => feedback({ action_id: action.id, action_status: s })}>{s === 'accepted' ? 'Plan to do' : s === 'completed' ? 'Done' : 'Not now'}</button>)}
      </div></div></article>
    })}</div>
    {analysis.warnings.length > 0 && <div className="considerations"><Info size={17} /><div><h3>A few things to keep in mind</h3><ul>{analysis.warnings.map(w => <li key={w}>{w}</li>)}</ul></div></div>}
    <section className="panel scenario-panel"><div className="section-title"><span className="note-icon"><TrendingUp size={19} /></span><div><h2>See what a small change could do</h2><p>Try a different flexible-spending budget. This preview isn’t saved.</p></div></div><div className="scenario-controls"><label className="field"><span className="field-label">Flexible spending / month</span><span className="money-input"><span>$</span><input aria-label="Scenario flexible spending" type="number" min="0" step="0.01" value={spending} onChange={e => { setSpending(e.target.value); setScenario(null) }} /></span></label><button className="button secondary" disabled={scenarioBusy || spending === ''} onClick={compare}>{scenarioBusy ? 'Comparing…' : 'Compare scenario'}<ArrowRight size={15} /></button></div>{scenario && <div className="scenario-result" role="status"><strong>{formatMoney(scenario.metrics.monthly_surplus)} monthly surplus</strong><p>{formatMoney(Number(scenario.metrics.monthly_surplus) - Number(analysis.metrics.monthly_surplus))} change from your saved plan.</p><p>First step: {scenario.actions[0]?.title} {scenario.actions[0]?.kind === 'allocation' && `: ${formatMoney(scenario.actions[0].amount)} / month`}</p></div>}</section>
    <section className="panel feedback-panel"><div><h3>Was this explanation useful?</h3><p>Your feedback helps us understand what’s clear and what needs work.</p></div><div className="rating-buttons"><button className={`button secondary ${overview?.rating === 'helpful' ? 'selected' : ''}`} aria-pressed={overview?.rating === 'helpful'} disabled={feedbackBusy} onClick={() => feedback({ action_id: 'overview', rating: 'helpful', comment })}><ThumbsUp size={15} /> Helpful</button><button className={`button secondary ${overview?.rating === 'not_helpful' ? 'selected' : ''}`} aria-pressed={overview?.rating === 'not_helpful'} disabled={feedbackBusy} onClick={() => feedback({ action_id: 'overview', rating: 'not_helpful', comment })}><ThumbsDown size={15} /> Could be clearer</button></div><details className="comment-detail"><summary>Leave a short note</summary><label className="field"><span className="field-label">What could be better?</span><textarea maxLength={500} value={comment} onChange={e => setComment(e.target.value)} placeholder="Please don’t include personal or account details." /></label><button className="button secondary" disabled={feedbackBusy || !comment.trim()} onClick={() => feedback({ action_id: 'overview', comment })}>Save note</button></details><p className="status-message" role="status">{notice}</p></section>
    <div className="audit-details"><details><summary><Info size={15} /> Assumptions & sources</summary><ul>{analysis.assumptions.map(a => <li key={a}>{a}</li>)}</ul><p>Rules {analysis.rules_version} · Prompt {analysis.prompt_version} · Sources reviewed {analysis.sources_version}</p><p>Educational guidance, not investment, tax or legal advice. No transfers or investments are executed.</p></details><details><summary><Code2 size={15} /> View API response</summary><pre>{JSON.stringify(analysis, null, 2)}</pre></details></div>
  </div>
}
